/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javazoom.jlgui.basicplayer.BasicPlayer;

/**
 *
 * @author Fercho
 */
public class Celular extends javax.swing.JFrame {

    int puntos=1;
    
    String id="";
    String R_correcta="";//Respuesta correcta
    String F_correcta="";/*Frase correcta*/
    String Ej1_img_ruta="";//Ruta de la imagen
    String Ej1_frase_sin_respuesta="";//Frase sin la respuesta correcta
    String Ej1_sonido_ayuda=""; //Dirección del Audio
    String Ej1_opcion1="";//Posible respuesta1;
    String Ej1_opcion2="";//Posible Respuesta2
    String Ej1_opcion3="";//Posible respuesta3
    
    public void Asignacion_de_valores(){
         id="1"+"_";
         R_correcta="manzana";//Respuesta correcta
         F_correcta="La "+R_correcta+" es Roja";/*Frase correcta*/
         Ej1_img_ruta="img/"+id+R_correcta+".png";//Ruta de la imagen
         Ej1_frase_sin_respuesta="La .........\nes Roja";//Frase sin la respuesta correcta
         Ej1_sonido_ayuda="audios"+"/"+id+R_correcta+".mp3"; //Dirección del Audio
         Ej1_opcion1="manzana";//Posible respuesta1;
         Ej1_opcion2="piña";//Posible Respuesta2
         Ej1_opcion3="uva";//Posible respuesta3
         ImageIcon imagen = new ImageIcon(Ej1_img_ruta);
         Imagen.setIcon(imagen);
    }
    boolean normal=true;
    
    public Celular() {
        initComponents();
        setSize(320, 570);
        OcultarPaneles();
        Asignacion_de_valores();
        VentanaCargando.setVisible(true); 
   }
    public void OcultarPaneles(){
        VentajaConfirmacionSalir.setVisible(false);
        VentanaCargando.setVisible(false);
        VentanaOpcionesdeRegistro.setVisible(false);
        RegistrarAlumnoMaestro.setVisible(false);
        RegistroAlumno.setVisible(false);
        RegistroMaestro.setVisible(false);
        Yatengocuenta.setVisible(false);
        VentanaPrincipal.setVisible(false);
        Ejercicio123.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        jPanel11.setVisible(false);
        jPanel12.setVisible(false);
        jPanel13.setVisible(false);
        Paneles_ventana_principal();
    }
    public void Paneles_ventana_principal()
    {
        VentanaPrincipalPanel1.setVisible(false);
        VentanaPrincipalPanel2.setVisible(false);
        VentanaPrincipalPanel3.setVisible(false);
        VentanaPrincipalPanel4.setVisible(false);
        VentanaPrincipalPanel5.setVisible(false);
        VentanaPrincipalPanel6.setVisible(false);
        
        VentanaPrincipalCerrarSesion.setVisible(false);
        Botones_visibles_VentanaPrincipal();
    }
    public void Botones_visibles_VentanaPrincipal(){
        jButton16.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        jButton21.setVisible(true);
        jButton22.setVisible(true);
        normal=true;
    }
    public void Ejercicio1_2_3(){
        if(puntos<=3){
        VentanaPrincipal.setVisible(false);
        Ejercicio123.setVisible(true);
        Contador.setText(""+puntos);
        Imagen.setText(Ej1_img_ruta);//Cambiar a ícono
        Pregunta.setText(Ej1_frase_sin_respuesta);
        opc1.setText(Ej1_opcion1);
        opc2.setText(Ej1_opcion2);
        opc3.setText(Ej1_opcion3);
        }else{
            System.out.println("Ejercicio 4 5 6");
        }
    }
    public void Ejercicio_Correcto(){
        System.out.println("Correcto");
        JOptionPane.showMessageDialog(null,"Correctó\nOración\n"+F_correcta);
        puntos++;
        Ejercicio1_2_3();
    }
    public void Ejercicio_Incorrecto(){
        reproducirsonido("sonidos/error.mp3");
        System.out.println("Incorrecto");
        JOptionPane.showMessageDialog(null,"Error\nRespuesta Correcta:\n"+R_correcta);
        Ejercicio1_2_3();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton37 = new javax.swing.JButton();
        VentajaConfirmacionSalir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        VentanaCargando = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        VentanaOpcionesdeRegistro = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        RegistrarAlumnoMaestro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        RegistroAlumno = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        RegistroMaestro = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Yatengocuenta = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        VentanaPrincipal = new javax.swing.JPanel();
        VentanaPrincipalPanel2 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        VentanaPrincipalPanel4 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        VentanaPrincipalPanel6 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        VentanaPrincipalPanel5 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        VentanaPrincipalPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        VentanaPrincipalPanel3 = new javax.swing.JPanel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        VentanaPrincipalCerrarSesion = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        Ejercicio123 = new javax.swing.JPanel();
        jButton36 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Pregunta = new javax.swing.JLabel();
        Pregunta1 = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        opc3 = new javax.swing.JButton();
        opc1 = new javax.swing.JButton();
        opc2 = new javax.swing.JButton();
        opc4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        jButton37.setText("jButton37");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        VentajaConfirmacionSalir.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("¿Está seguro");
        VentajaConfirmacionSalir.add(jLabel3);
        jLabel3.setBounds(40, 110, 210, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("que desea Salir?");
        VentajaConfirmacionSalir.add(jLabel4);
        jLabel4.setBounds(20, 180, 260, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setText("No");
        VentajaConfirmacionSalir.add(jButton2);
        jButton2.setBounds(170, 320, 100, 53);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton3.setText("Si");
        VentajaConfirmacionSalir.add(jButton3);
        jButton3.setBounds(30, 320, 100, 53);

        getContentPane().add(VentajaConfirmacionSalir);
        VentajaConfirmacionSalir.setBounds(0, 0, 300, 500);

        VentanaCargando.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("ZapApp");
        VentanaCargando.add(jLabel6);
        jLabel6.setBounds(80, 150, 210, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton4.setText("Comenzar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        VentanaCargando.add(jButton4);
        jButton4.setBounds(40, 300, 220, 53);

        getContentPane().add(VentanaCargando);
        VentanaCargando.setBounds(0, 0, 300, 500);

        VentanaOpcionesdeRegistro.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("ZapApp");
        VentanaOpcionesdeRegistro.add(jLabel7);
        jLabel7.setBounds(90, 200, 140, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Bienvendido");
        VentanaOpcionesdeRegistro.add(jLabel8);
        jLabel8.setBounds(50, 90, 210, 60);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("a");
        VentanaOpcionesdeRegistro.add(jLabel9);
        jLabel9.setBounds(140, 150, 40, 60);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton5.setText("Ya tengo cuenta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        VentanaOpcionesdeRegistro.add(jButton5);
        jButton5.setBounds(0, 370, 300, 53);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton6.setText("Registrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        VentanaOpcionesdeRegistro.add(jButton6);
        jButton6.setBounds(40, 300, 220, 53);

        getContentPane().add(VentanaOpcionesdeRegistro);
        VentanaOpcionesdeRegistro.setBounds(0, 0, 300, 500);

        RegistrarAlumnoMaestro.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("como:");
        RegistrarAlumnoMaestro.add(jLabel10);
        jLabel10.setBounds(100, 170, 110, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Resgistrar");
        RegistrarAlumnoMaestro.add(jLabel11);
        jLabel11.setBounds(70, 110, 170, 60);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton7.setText("Maestro");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        RegistrarAlumnoMaestro.add(jButton7);
        jButton7.setBounds(70, 350, 170, 53);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton8.setText("Atrás");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        RegistrarAlumnoMaestro.add(jButton8);
        jButton8.setBounds(170, 0, 130, 53);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton9.setText("Alumno");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        RegistrarAlumnoMaestro.add(jButton9);
        jButton9.setBounds(70, 270, 170, 53);

        getContentPane().add(RegistrarAlumnoMaestro);
        RegistrarAlumnoMaestro.setBounds(0, 0, 300, 500);

        RegistroAlumno.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Registro de");
        RegistroAlumno.add(jLabel13);
        jLabel13.setBounds(60, 60, 270, 60);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Opcional:");
        RegistroAlumno.add(jLabel14);
        jLabel14.setBounds(80, 270, 270, 60);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setText("e-mail");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        RegistroAlumno.add(jTextField1);
        jTextField1.setBounds(20, 320, 260, 50);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField2.setText("Nombre(s)");
        RegistroAlumno.add(jTextField2);
        jTextField2.setBounds(20, 170, 260, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setText("Alumno");
        RegistroAlumno.add(jLabel15);
        jLabel15.setBounds(90, 110, 270, 60);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField3.setText("Apellido(s)");
        RegistroAlumno.add(jTextField3);
        jTextField3.setBounds(20, 230, 260, 50);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton10.setText("Registrar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        RegistroAlumno.add(jButton10);
        jButton10.setBounds(60, 390, 180, 53);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton11.setText("Atrás");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        RegistroAlumno.add(jButton11);
        jButton11.setBounds(170, 0, 130, 53);

        getContentPane().add(RegistroAlumno);
        RegistroAlumno.setBounds(0, 0, 300, 500);

        RegistroMaestro.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("Registro de");
        RegistroMaestro.add(jLabel16);
        jLabel16.setBounds(60, 70, 270, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel17.setText("Opcional:");
        RegistroMaestro.add(jLabel17);
        jLabel17.setBounds(80, 320, 270, 60);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField4.setText("e-mail");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        RegistroMaestro.add(jTextField4);
        jTextField4.setBounds(20, 370, 260, 50);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField5.setText("Nombre(s)");
        RegistroMaestro.add(jTextField5);
        jTextField5.setBounds(20, 200, 260, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("Maestro");
        RegistroMaestro.add(jLabel18);
        jLabel18.setBounds(90, 130, 270, 60);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField6.setText("Apellido(s)");
        RegistroMaestro.add(jTextField6);
        jTextField6.setBounds(20, 260, 260, 50);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton12.setText("Registrar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        RegistroMaestro.add(jButton12);
        jButton12.setBounds(60, 430, 180, 53);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton13.setText("Atrás");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        RegistroMaestro.add(jButton13);
        jButton13.setBounds(170, 0, 130, 53);

        getContentPane().add(RegistroMaestro);
        RegistroMaestro.setBounds(0, 0, 300, 500);

        Yatengocuenta.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel19.setText("Bienvenidos");
        Yatengocuenta.add(jLabel19);
        jLabel19.setBounds(60, 90, 270, 60);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField7.setText("e-mail");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        Yatengocuenta.add(jTextField7);
        jTextField7.setBounds(20, 290, 260, 50);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField8.setText("Nombre(s)");
        Yatengocuenta.add(jTextField8);
        jTextField8.setBounds(20, 170, 260, 50);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField9.setText("Apellido(s)");
        Yatengocuenta.add(jTextField9);
        jTextField9.setBounds(20, 230, 260, 50);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton14.setText("Ingresar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        Yatengocuenta.add(jButton14);
        jButton14.setBounds(60, 360, 180, 53);

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton15.setText("Atrás");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Yatengocuenta.add(jButton15);
        jButton15.setBounds(170, 0, 130, 53);

        getContentPane().add(Yatengocuenta);
        Yatengocuenta.setBounds(0, 0, 300, 500);

        VentanaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalMouseEntered(evt);
            }
        });
        VentanaPrincipal.setLayout(null);

        VentanaPrincipalPanel2.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel2MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel2.setLayout(null);

        jButton24.setText("Cancelar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel2.add(jButton24);
        jButton24.setBounds(10, 56, 81, 23);

        jButton25.setText("Comenzar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel2.add(jButton25);
        jButton25.setBounds(10, 11, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel2);
        VentanaPrincipalPanel2.setBounds(170, 90, 100, 90);

        VentanaPrincipalPanel4.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel4MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel4.setLayout(null);

        jButton28.setText("Cancelar");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel4.add(jButton28);
        jButton28.setBounds(10, 56, 81, 23);

        jButton29.setText("Comenzar");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel4.add(jButton29);
        jButton29.setBounds(10, 11, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel4);
        VentanaPrincipalPanel4.setBounds(171, 210, 100, 90);

        VentanaPrincipalPanel6.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel6MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel6.setLayout(null);

        jButton32.setText("Cancelar");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel6.add(jButton32);
        jButton32.setBounds(10, 56, 81, 23);

        jButton33.setText("Comenzar");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel6.add(jButton33);
        jButton33.setBounds(10, 11, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel6);
        VentanaPrincipalPanel6.setBounds(171, 330, 100, 90);

        VentanaPrincipalPanel5.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel5MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel5.setLayout(null);

        jButton30.setText("Cancelar");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel5.add(jButton30);
        jButton30.setBounds(10, 56, 81, 23);

        jButton31.setText("Comenzar");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel5.add(jButton31);
        jButton31.setBounds(10, 15, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel5);
        VentanaPrincipalPanel5.setBounds(51, 330, 100, 90);

        VentanaPrincipalPanel1.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                VentanaPrincipalPanel1FocusLost(evt);
            }
        });
        VentanaPrincipalPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel1MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel1.setLayout(null);

        jButton1.setText("Comenzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel1.add(jButton1);
        jButton1.setBounds(10, 11, 81, 23);

        jButton23.setText("Cancelar");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel1.add(jButton23);
        jButton23.setBounds(10, 56, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel1);
        VentanaPrincipalPanel1.setBounds(51, 90, 100, 90);

        VentanaPrincipalPanel3.setBackground(new java.awt.Color(153, 255, 153));
        VentanaPrincipalPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalPanel3MouseEntered(evt);
            }
        });
        VentanaPrincipalPanel3.setLayout(null);

        jButton26.setText("Cancelar");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel3.add(jButton26);
        jButton26.setBounds(10, 56, 81, 23);

        jButton27.setText("Comenzar");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        VentanaPrincipalPanel3.add(jButton27);
        jButton27.setBounds(10, 11, 81, 23);

        VentanaPrincipal.add(VentanaPrincipalPanel3);
        VentanaPrincipalPanel3.setBounds(51, 210, 100, 90);

        VentanaPrincipalCerrarSesion.setBackground(new java.awt.Color(102, 255, 204));
        VentanaPrincipalCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentanaPrincipalCerrarSesionMouseEntered(evt);
            }
        });
        VentanaPrincipalCerrarSesion.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel22.setText("Luis Fernando");
        VentanaPrincipalCerrarSesion.add(jLabel22);
        jLabel22.setBounds(30, 0, 240, 50);

        jButton34.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton34.setText("Cancel");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        VentanaPrincipalCerrarSesion.add(jButton34);
        jButton34.setBounds(160, 60, 140, 40);

        jButton35.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton35.setText("Cerrar");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        VentanaPrincipalCerrarSesion.add(jButton35);
        jButton35.setBounds(10, 60, 140, 40);

        VentanaPrincipal.add(VentanaPrincipalCerrarSesion);
        VentanaPrincipalCerrarSesion.setBounds(0, 0, 290, 90);

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton16.setText("Animales");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton16);
        jButton16.setBounds(170, 93, 100, 90);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton17.setText("Comida");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton17);
        jButton17.setBounds(50, 93, 100, 90);

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton18.setText("Transporte");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton18);
        jButton18.setBounds(50, 210, 100, 90);

        jButton19.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton19.setText("Ropa");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton19);
        jButton19.setBounds(170, 210, 100, 90);

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton20.setText("Deportes");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton20);
        jButton20.setBounds(50, 330, 100, 90);

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton21.setText("Personas");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton21);
        jButton21.setBounds(170, 330, 100, 90);

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton22.setText("...");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        VentanaPrincipal.add(jButton22);
        jButton22.setBounds(220, 10, 60, 53);

        getContentPane().add(VentanaPrincipal);
        VentanaPrincipal.setBounds(0, 0, 300, 500);

        Ejercicio123.setLayout(null);

        jButton36.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton36.setText("Salir");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        Ejercicio123.add(jButton36);
        jButton36.setBounds(200, 10, 100, 53);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setText("/10");
        Ejercicio123.add(jLabel21);
        jLabel21.setBounds(40, 10, 80, 60);
        Ejercicio123.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 300, 2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Completa las siguientes");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 0, 270, 60);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("oraciones");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 40, 140, 60);

        Ejercicio123.add(jPanel1);
        jPanel1.setBounds(10, 80, 280, 90);

        Pregunta.setBackground(new java.awt.Color(204, 204, 204));
        Pregunta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pregunta.setText("AAAAAAAAAAAAAAAAA");
        Ejercicio123.add(Pregunta);
        Pregunta.setBounds(20, 310, 260, 50);

        Pregunta1.setBackground(new java.awt.Color(204, 204, 204));
        Pregunta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pregunta1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercho\\Documents\\NetBeansProjects\\AZ\\img\\Fondos_preguntas.jpg")); // NOI18N
        Pregunta1.setText("Ayuda");
        Ejercicio123.add(Pregunta1);
        Pregunta1.setBounds(20, 310, 260, 50);

        Imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fercho\\Documents\\NetBeansProjects\\AZ\\img\\1_manzana.png")); // NOI18N
        Ejercicio123.add(Imagen);
        Imagen.setBounds(40, 180, 210, 220);

        Contador.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Contador.setText("0");
        Ejercicio123.add(Contador);
        Contador.setBounds(10, 10, 80, 60);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel25.setText("LOGO");
        Ejercicio123.add(jLabel25);
        jLabel25.setBounds(100, 10, 100, 60);

        opc3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        opc3.setText("...");
        opc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc3ActionPerformed(evt);
            }
        });
        Ejercicio123.add(opc3);
        opc3.setBounds(90, 440, 130, 60);

        opc1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        opc1.setText("...");
        opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc1ActionPerformed(evt);
            }
        });
        Ejercicio123.add(opc1);
        opc1.setBounds(20, 370, 120, 60);

        opc2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        opc2.setText("...");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });
        Ejercicio123.add(opc2);
        opc2.setBounds(160, 370, 120, 60);

        opc4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        opc4.setText("...");
        opc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc4ActionPerformed(evt);
            }
        });
        Ejercicio123.add(opc4);
        opc4.setBounds(230, 180, 60, 40);

        getContentPane().add(Ejercicio123);
        Ejercicio123.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11);
        jPanel11.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12);
        jPanel12.setBounds(0, 0, 300, 500);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13);
        jPanel13.setBounds(0, 0, 300, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Yatengocuenta.setVisible(true);
        VentanaOpcionesdeRegistro.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        RegistrarAlumnoMaestro.setVisible(true);
        VentanaOpcionesdeRegistro.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        RegistroMaestro.setVisible(true);
        RegistrarAlumnoMaestro.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        VentanaOpcionesdeRegistro.setVisible(true);
        RegistrarAlumnoMaestro.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        RegistroAlumno.setVisible(true);
        RegistrarAlumnoMaestro.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        RegistroAlumno.setVisible(false);
        VentanaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        RegistroAlumno.setVisible(false);
        RegistrarAlumnoMaestro.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        RegistroMaestro.setVisible(false);
        VentanaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        VentanaCargando.setVisible(false);
        VentanaOpcionesdeRegistro.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Yatengocuenta.setVisible(false);
        VentanaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Yatengocuenta.setVisible(false);
        VentanaOpcionesdeRegistro.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jButton16.setVisible(false);
        VentanaPrincipalPanel2.setVisible(true);      
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jButton17.setVisible(false);
        VentanaPrincipalPanel1.setVisible(true);
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jButton18.setVisible(false);
        VentanaPrincipalPanel3.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jButton19.setVisible(false);
        VentanaPrincipalPanel4.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        jButton20.setVisible(false);
        VentanaPrincipalPanel5.setVisible(true);
        VentanaPrincipalPanel5.setFocusable(true);
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jButton21.setVisible(false);
        VentanaPrincipalPanel6.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jButton22.setVisible(false);
        VentanaPrincipalCerrarSesion.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        VentanaPrincipalPanel1.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        VentanaPrincipalPanel2.setVisible(false);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        VentanaPrincipalPanel3.setVisible(false);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        VentanaPrincipalPanel4.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        VentanaPrincipalPanel5.setVisible(false);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        VentanaPrincipalPanel6.setVisible(false);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        VentanaPrincipalCerrarSesion.setVisible(false);
        Botones_visibles_VentanaPrincipal();
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        VentanaPrincipalCerrarSesion.setVisible(false);
        VentanaPrincipal.setVisible(false);
        OcultarPaneles();
        VentanaOpcionesdeRegistro.setVisible(true);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OcultarPaneles();
        Ejercicio1_2_3();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        OcultarPaneles();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        OcultarPaneles();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        OcultarPaneles();
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        OcultarPaneles();
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        OcultarPaneles();
    }//GEN-LAST:event_jButton33ActionPerformed

    private void VentanaPrincipalPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel1FocusLost
    }//GEN-LAST:event_VentanaPrincipalPanel1FocusLost

    private void VentanaPrincipalPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel1MouseEntered
        System.out.println("El Mouse ingresa p1");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel1MouseEntered

    private void VentanaPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalMouseEntered
        //System.out.println("Mouse normal");
        Paneles_ventana_principal();
        if(!normal)
           Botones_visibles_VentanaPrincipal();
    }//GEN-LAST:event_VentanaPrincipalMouseEntered

    private void VentanaPrincipalPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel2MouseEntered
        System.out.println("El Mouse ingresa p2");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel2MouseEntered

    private void VentanaPrincipalPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel3MouseEntered
        System.out.println("El Mouse ingresa p3");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel3MouseEntered

    private void VentanaPrincipalPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel4MouseEntered
        System.out.println("El Mouse ingresa p4");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel4MouseEntered

    private void VentanaPrincipalPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel5MouseEntered
        System.out.println("El Mouse ingresa p5");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel5MouseEntered

    private void VentanaPrincipalPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalPanel6MouseEntered
        System.out.println("El Mouse ingresa p6");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalPanel6MouseEntered

    private void VentanaPrincipalCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanaPrincipalCerrarSesionMouseEntered
        System.out.println("El Mouse ingresa a Cerrar Sesión");
        normal=false;
    }//GEN-LAST:event_VentanaPrincipalCerrarSesionMouseEntered

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void opc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc3ActionPerformed
        if(R_correcta.equals(opc3.getText()))
            Ejercicio_Correcto();
        else{
            Ejercicio_Incorrecto();
        }
    }//GEN-LAST:event_opc3ActionPerformed

    private void opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc1ActionPerformed
        if(R_correcta.equals(opc1.getText()))
            Ejercicio_Correcto();
        else{
            Ejercicio_Incorrecto();
        }
    }//GEN-LAST:event_opc1ActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
        if(R_correcta.equals(opc2.getText()))
            Ejercicio_Correcto();
        else{
            Ejercicio_Incorrecto();
        }
    }//GEN-LAST:event_opc2ActionPerformed

    private void opc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc4ActionPerformed
        reproducirsonido(Ej1_sonido_ayuda);
        
        
        
        
        try {
            System.out.println("Audio de ejemplo");
            
            File miDir = new File (".");
            System.out.println ("Directorio actual: " + miDir.getCanonicalPath());
            
        } catch (IOException ex) {
            Logger.getLogger(Celular.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_opc4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Celular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contador;
    private javax.swing.JPanel Ejercicio123;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Pregunta;
    private javax.swing.JLabel Pregunta1;
    private javax.swing.JPanel RegistrarAlumnoMaestro;
    private javax.swing.JPanel RegistroAlumno;
    private javax.swing.JPanel RegistroMaestro;
    private javax.swing.JPanel VentajaConfirmacionSalir;
    private javax.swing.JPanel VentanaCargando;
    private javax.swing.JPanel VentanaOpcionesdeRegistro;
    private javax.swing.JPanel VentanaPrincipal;
    private javax.swing.JPanel VentanaPrincipalCerrarSesion;
    private javax.swing.JPanel VentanaPrincipalPanel1;
    private javax.swing.JPanel VentanaPrincipalPanel2;
    private javax.swing.JPanel VentanaPrincipalPanel3;
    private javax.swing.JPanel VentanaPrincipalPanel4;
    private javax.swing.JPanel VentanaPrincipalPanel5;
    private javax.swing.JPanel VentanaPrincipalPanel6;
    private javax.swing.JPanel Yatengocuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton opc1;
    private javax.swing.JButton opc2;
    private javax.swing.JButton opc3;
    private javax.swing.JButton opc4;
    // End of variables declaration//GEN-END:variables

    private void reproducirsonido(String sonidoserrormp3) {
      
        try {
               BasicPlayer sonido = new BasicPlayer();
                sonido.open(new File(sonidoserrormp3));
                sonido.play();
         } catch (Exception e) {
                System.out.println(e);
         }
    }        
    
}
